# Generated by Django 4.2.30 on 2026-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaitem',
            name='show_in_multimedia',
            field=models.BooleanField(default=True),
        ),
    ]
