# Generated by Django 4.2.30 on 2026-04-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_multimediaitem_show_in_multimedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(default='Open media', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('multimedia_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_links', to='editor.multimediaitem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_media_links', to='editor.page')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
