# Generated by Django 4.2.30 on 2026-04-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_articlevideo_articleimage_articleaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleaudio',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='articlevideo',
            name='page',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='editor.page')),
            ],
        ),
        migrations.AddField(
            model_name='articleaudio',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='editor.article'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='editor.article'),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='editor.article'),
        ),
    ]
